server:
port: 8080

spring:
datasource:
url: jdbc:h2:mem:testdb
h2:
console:
enabled: true
jpa:
hibernate:
ddl-auto: update
show-sql: true

slack:
  webhook:
    url: "https://hooks.slack.com/services/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"